from celery import shared_task
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
# from .models import BroadcastNotification
from .models import BroadcastNotification
import json
from celery import Celery, states
from asgiref.sync import async_to_sync
from celery.exceptions import Ignore
import asyncio


@shared_task(bind=True)
def broadcast_notification(self, notification_id):
    print("Task started with ID:", notification_id)
    try:
        # Queryset ‡¶è‡¶∞ ‡¶™‡¶∞‡¶ø‡¶¨‡¶∞‡ßç‡¶§‡ßá ‡¶∏‡¶∞‡¶æ‡¶∏‡¶∞‡¶ø get ‡¶¨‡ßç‡¶Ø‡¶¨‡¶π‡¶æ‡¶∞ ‡¶ï‡¶∞‡ßã
        notification = BroadcastNotification.objects.get(id=int(notification_id))
        print("Notification found:", notification.message)

        channel_layer = get_channel_layer()
        print("Channel layer:", channel_layer)

        async_to_sync(channel_layer.group_send)(
            "notification_broadcast",
            {
                "type": "send_notification",
                "message": json.dumps({
                    "text": notification.message,
                    "type": "info"
                }),
            }
        )
        print("Message sent to group!")

        notification.sent = True
        notification.save()
        print("Notification updated as sent!")

        return "Done"

    except BroadcastNotification.DoesNotExist:
        print("Notification not found with ID:", notification_id)
        self.update_state(
            state="FAILURE",
            meta={"exe": "Not Found"}
        )
        raise Ignore()

    except Exception as e:
        print("Unexpected error in Celery Task:", str(e))
        import traceback
        print(traceback.format_exc())   # üî• ‡¶Ü‡¶∏‡¶≤ error stacktrace ‡¶¶‡ßá‡¶ñ‡¶æ‡¶¨‡ßá

        self.update_state(
            state="FAILURE",
            meta={"exe": f"Failed: {str(e)}"}
        )
        raise Ignore()
